# Generated by Django 6.0 on 2025-12-28 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduction_initiated', models.DateTimeField(auto_now_add=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(related_name='curated_introductions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_interaction'],
            },
        ),
        migrations.CreateModel(
            name='DiscreetMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('exchanged_at', models.DateTimeField(auto_now_add=True)),
                ('introduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discreet_messages', to='main.curatedintroduction')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_exchanges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['exchanged_at'],
            },
        ),
        migrations.AddField(
            model_name='curatedintroduction',
            name='last_exchange',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_in_introduction', to='main.discreetmessage'),
        ),
        migrations.CreateModel(
            name='ExclusiveExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_title', models.CharField(max_length=200)),
                ('venue', models.CharField(max_length=200)),
                ('experience_date', models.DateField()),
                ('commencement', models.TimeField()),
                ('conclusion', models.TimeField()),
                ('experience_description', models.TextField()),
                ('consideration', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('consideration_type', models.CharField(choices=[('hosted_experience', 'Hosted Experience'), ('seeking_participant', 'Seeking Participant')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('listed_at', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_experiences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LifestyleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('gender_preference', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], default='Both', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('primary_location', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('portfolio_image', models.ImageField(blank=True, null=True, upload_to='portfolios/')),
                ('personal_statement', models.TextField(blank=True)),
                ('lifestyle_preference', models.CharField(blank=True, choices=[('curated_connections', 'Curated Connections'), ('luxury_experiences', 'Luxury Experiences'), ('mutual_benefit', 'Mutual Benefit')], max_length=50)),
                ('current_engagement', models.CharField(blank=True, choices=[('discreetly_available', 'Discreetly Available'), ('selectively_engaged', 'Selectively Engaged'), ('unattached', 'Unattached'), ('complicated_elegance', 'Complicated Elegance')], max_length=50)),
                ('physique', models.CharField(blank=True, choices=[('Slim', 'Slim'), ('Average', 'Average'), ('Athletic', 'Athletic'), ('Large', 'Large'), ('Curvy', 'Curvy')], max_length=50)),
                ('family_considerations', models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes'), ('Yes, at home', 'Yes, at home'), ('Yes, not at home', 'Yes, not at home')], max_length=50)),
                ('lifestyle_habits', models.CharField(blank=True, choices=[('No', 'No'), ('Yes', 'Yes'), ('Socially', 'Socially')], max_length=50)),
                ('stature', models.CharField(blank=True, choices=[('Select from list', 'Select from list'), ('5\'0"', '5\'0"'), ('5\'5"', '5\'5"'), ('5\'10"', '5\'10"'), ('6\'0"', '6\'0"'), ('6\'5"', '6\'5"')], max_length=50)),
                ('financial_capacity', models.CharField(blank=True, choices=[('Under $100k', 'Under $100k'), ('$100k - $250k', '$100k - $250k'), ('$250k - $500k', '$250k - $500k'), ('$500k - $1M', '$500k - $1M'), ('$1M - $5M', '$1M - $5M'), ('Over $5M', 'Over $5M')], max_length=50)),
                ('personal_philosophy', models.TextField(blank=True)),
                ('seeking_qualities', models.TextField(blank=True)),
                ('preferred_engagements', models.JSONField(default=list)),
                ('appreciates_qualities', models.JSONField(default=list)),
                ('availability_framework', models.JSONField(default=list)),
                ('expectation_framework', models.CharField(blank=True, max_length=100)),
                ('consideration_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('consideration_period', models.CharField(blank=True, choices=[('per week', 'per week'), ('per month', 'per month'), ('per meet', 'per meet')], max_length=50)),
                ('engagement_tier', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('exclusive', 'Exclusive')], default='standard', max_length=20)),
                ('portfolio_suspended', models.BooleanField(default=False)),
                ('curator_approved', models.BooleanField(default=False)),
                ('public_portfolio', models.BooleanField(default=False)),
                ('under_review', models.BooleanField(default=True)),
                ('enhanced_portfolio', models.BooleanField(default=False)),
                ('curated_content', models.JSONField(blank=True, null=True)),
                ('lifestyle_images', models.JSONField(default=list)),
                ('private_gallery', models.JSONField(default=list)),
                ('gallery_access', models.JSONField(default=dict)),
                ('gallery_requests', models.JSONField(default=dict)),
                ('saved_connections', models.JSONField(default=list)),
                ('restricted_connections', models.JSONField(default=list)),
                ('portfolio_views', models.JSONField(default=dict)),
                ('interest_received', models.JSONField(default=dict)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('engagement_expiry', models.IntegerField(blank=True, null=True)),
                ('portfolio_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lifestyle_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_status', models.CharField(choices=[('pending_review', 'Pending Review'), ('access_granted', 'Access Granted'), ('access_declined', 'Access Declined')], default='pending_review', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('gallery_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_requests_received', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_requests_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('requester', 'gallery_owner')},
            },
        ),
    ]
